# automatically expand info properties from the Maven project using resource filtering
info.build.artifact: '@project.artifactId@'
info.build.name: '@project.name@'
info.build.description: '@project.description@'
info.build.version: '@project.version@'

direct:
  config:
    service:
      url:  http://localhost:8080/config-service

spring:
  cloud:
    stream:
      source: direct-smtp-gateway-message
      bindings:
        direct-smtp-gateway-message-out-0:
          destination: direct-smtp-mq-gateway
